services:
  mongodb:
    container_name: mongodb_service
    image: "mongo:latest"

  
  redis:
    container_name: redis_service
    image: "redis:latest"


  app:
    container_name: hello-wops
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - REDIS_HOST=redis_db
      - REDIS_PORT=6379
      - PORT=3000
